export class Cards {

	CardCollection = {
		"snowflipper penguin": true,
		"acherus veteran": true,
		"breath of sindragosa": true,
		"deadscale knight": true,
		"animated berserker": true,
		"play dead": true,
		"righteous protector": true,
		"sanguine reveler": true,
		"wretched tiller": true,
		"brrrloc": true,
		"dark conviction": true,
		"drain soul": true,
		"fallen sun cleric": true,
		"forge of souls": true,
		"ice fishing": true,
		"leeching poison": true,
		"shadow ascendant": true,
		"spirit lash": true,
		"tainted zealot": true,
		"tuskarr fisherman": true,
		"acolyte of agony": true,
		"bearshark": true,
		"coldwraith": true,
		"crypt lord": true,
		"deathspeaker": true,
		"drakkari defender": true,
		"frozen clone": true,
		"gnash": true,
		"howlfiend": true,
		"hyldnir frostrider": true,
		"plague scientist": true,
		"stitched tracker": true,
		"vryghoul": true,
		"blood razor": true,
		"chillblade champion": true,
		"grave shambler": true,
		"grim necromancer": true,
		"night howler": true,
		"wicked skeleton": true,
		"bloodworm": true,
		"bone baron": true,
		"cobalt scalebane": true,
		"skelemancer": true,
		"sunborne val'kyr": true,
		"venomancer": true,
		"webweave": true,
		"necrotic geist": true,
		"spellweaver": true,
		"bonemare": true,
		"defile": true,
		"desperate stand": true,
		"druid of the swarm": true,
		"ice walker": true,
		"roll the bones": true,
		"venomstrike trap": true,
		"doomed apprentice": true,
		"happy ghoul": true,
		"howling commander": true,
		"ice breaker": true,
		"mindbreaker": true,
		"mountainfire armor": true,
		"shadowblade": true,
		"shallow gravedigger": true,
		"unwilling sacrifice": true,
		"val'kyr soulclaimer": true,
		"arrogant crusader": true,
		"avalanche": true,
		"eternal servitude": true,
		"exploding bloatbat": true,
		"ghastly conjurer": true,
		"keening banshee": true,
		"phantom freebooter": true,
		"runeforge haunter": true,
		"saronite chain gang": true,
		"strongshell scavenger": true,
		"ticking abomination": true,
		"corpse raiser": true,
		"corpse widow": true,
		"death revenant": true,
		"despicable dreadlord": true,
		"devour mind": true,
		"spreading plague": true,
		"voodoo hexxer": true,
		"bone drake": true,
		"shadow essence": true,
		"doomerang": true,
		"bring it on!": true,
		"cryostasis": true,
		"dead man's hand": true,
		"gnomeferatu": true,
		"toxic arrow": true,
		"drakkari enchanter": true,
		"simulacrum": true,
		"treachery": true,
		"corpsetaker": true,
		"deathaxe punisher": true,
		"light's sorrow": true,
		"meat wagon": true,
		"rattling rascal": true,
		"fatespinner": true,
		"tomb lurker": true,
		"blackguard": true,
		"embrace darkness": true,
		"furnacefire colossus": true,
		"nerubian unraveler": true,
		"skulking geist": true,
		"spectral pillager": true,
		"abominable bowman": true,
		"glacial mysteries": true,
		"obsidian statue": true,
		"ultimate infestation": true,
		"snowfury giant": true,
		"prince keleseth": true,
		"prince taldaram": true,
		"arfus": true,
		"lilian voss": true,
		"prince valanar": true,
		"professor putricide": true,
		"blood-queen lana'thel": true,
		"bolvar, fireblood": true,
		"thrall, deathseer": true,
		"deathstalker rexxar": true,
		"moorabi": true,
		"archbishop benedictus": true,
		"malfurion the pestilent": true,
		"rotface": true,
		"scourgelord garrosh": true,
		"shadowreaper anduin": true,
		"sindragosa": true,
		"the lich king": true,
		"frost lich jaina": true,
		"hadronox": true,
		"uther of the ebon blade": true,
		"valeera the hollow": true,
		"bloodreaver gul'dan": true,
		"adaptation": true,
		"air elemental": true,
		"binding heal": true,
		"emerald reaver": true,
		"fire fly": true,
		"glacial shard": true,
		"hallucination": true,
		"iron hide": true,
		"jeweled macaw": true,
		"lost in the jungle": true,
		"arcanologist": true,
		"crackling razormaw": true,
		"flame geyser": true,
		"grievous bite": true,
		"hydrologist": true,
		"radiant elemental": true,
		"ravasaur runt": true,
		"razorpetal lasher": true,
		"razorpetal volley": true,
		"rockpool hunter": true,
		"shimmering tempest": true,
		"stubborn gastropod": true,
		"tortollan forager": true,
		"volatile elemental": true,
		"eggnapper": true,
		"elder longneck": true,
		"giant wasp": true,
		"hot spring guardian": true,
		"igneous elemental": true,
		"primalfin lookout": true,
		"pterrordax hatchling": true,
		"tar creeper": true,
		"thunder lizard": true,
		"fire plume phoenix": true,
		"lakkari felhound": true,
		"ravenous pterrordax": true,
		"stegodon": true,
		"tidal surge": true,
		"tortollan shellraiser": true,
		"nesting roc": true,
		"tar lurker": true,
		"verdant longneck": true,
		"ornery direhorn": true,
		"sabretooth stalker": true,
		"sated threshadon": true,
		"stormwatcher": true,
		"tar lord": true,
		"giant mastodon": true,
		"ultrasaur": true,
		"crystalline oracle": true,
		"earthen scales": true,
		"molten blade": true,
		"raptor hatchling": true,
		"cornered sentry": true,
		"corrupting mist": true,
		"fire plume harbinger": true,
		"golakka crawler": true,
		"primalfin totem": true,
		"devilsaur egg": true,
		"envenom weapon": true,
		"humongous razorleaf": true,
		"mana bind": true,
		"mimic pod": true,
		"mirage caller": true,
		"stonehill defender": true,
		"terrorscale stalker": true,
		"vicious fledgling": true,
		"evolving spores": true,
		"lightfused stegodon": true,
		"molten reflection": true,
		"obsidian shard": true,
		"shellshifter": true,
		"steam surger": true,
		"tol'vir stoneshaper": true,
		"direhorn hatchling": true,
		"feeding time": true,
		"servant of kalimos": true,
		"tol'vir warden": true,
		"volcano": true,
		"cruel dinomancer": true,
		"frozen crusher": true,
		"spikeridged steed": true,
		"vinecleaver": true,
		"volcanosaur": true,
		"free from amber": true,
		"emerald hive queen": true,
		"stampede": true,
		"biteweed": true,
		"bloodbloom": true,
		"dinomancy": true,
		"explore un'goro": true,
		"primalfin champion": true,
		"primordial glyph": true,
		"shadow visions": true,
		"chittering tunneler": true,
		"curious glimmerroot": true,
		"gluttonous ooze": true,
		"spirit echo": true,
		"bright-eyed scout": true,
		"gentle megasaur": true,
		"bittertide hydra": true,
		"living mana": true,
		"sudden genesis": true,
		"vilespine slayer": true,
		"meteor": true,
		"blazecaller": true,
		"giant anaconda": true,
		"stone sentinel": true,
		"charged devilsaur": true,
		"dinosize": true,
		"primordial drake": true,
		"tortollan primalist": true,
		"awaken the makers": true,
		"fire plume's heart": true,
		"jungle giants": true,
		"lakkari sacrifice": true,
		"open the waygate": true,
		"the caverns below": true,
		"the last kaleidosaur": true,
		"the marsh queen": true,
		"unite the murlocs": true,
		"clutchmother zavas": true,
		"pyros": true,
		"sherazin, corpse flower": true,
		"spiritsinger umbra": true,
		"the voraxx": true,
		"elise the trailblazer": true,
		"lyra the sunshard": true,
		"hemet, jungle hunter": true,
		"sunkeeper tarim": true,
		"swamp king dred": true,
		"kalimos, primal lord": true,
		"king mosh": true,
		"ozruk": true,
		"tyrantus": true,
		"freezing potion": true,
		"alleycat": true,
		"grimscale chum": true,
		"i know a guy": true,
		"kabal lackey": true,
		"mark of the lotus": true,
		"mistress of mixtures": true,
		"potion of madness": true,
		"smuggler's crate": true,
		"smuggler's run": true,
		"blowgill sniper": true,
		"friendly bartender": true,
		"gadgetzan socialite": true,
		"grimestreet outfitter": true,
		"jade shuriken": true,
		"jade swarmer": true,
		"public defender": true,
		"backstreet leper": true,
		"grimestreet smuggler": true,
		"hired gun": true,
		"jade blossom": true,
		"kabal talonpriest": true,
		"shadow rager": true,
		"shaky zipgunner": true,
		"street trickster": true,
		"toxic sewer ooze": true,
		"blastcrystal potion": true,
		"call in the finishers": true,
		"crystalweaver": true,
		"daring reporter": true,
		"grimy gadgeteer": true,
		"hozen healer": true,
		"jade lightning": true,
		"jade spirit": true,
		"kabal chemist": true,
		"kooky chemist": true,
		"naga corsair": true,
		"tanaris hogchopper": true,
		"worgen greaser": true,
		"cryomancer": true,
		"grook fu master": true,
		"kabal songstealer": true,
		"red mana wyrm": true,
		"streetwise investigator": true,
		"ancient of blossoms": true,
		"big-time racketeer": true,
		"jade behemoth": true,
		"abyssal enforcer": true,
		"jade chieftain": true,
		"counterfeit coin": true,
		"getaway kodo": true,
		"jade idol": true,
		"pint-size potion": true,
		"small-time buccaneer": true,
		"devolve": true,
		"gadgetzan ferryman": true,
		"grimestreet informant": true,
		"hidden cache": true,
		"jade claws": true,
		"stolen goods": true,
		"trogg beastrager": true,
		"bloodfury potion": true,
		"celestial dreamer": true,
		"grimestreet pawnbroker": true,
		"kabal courier": true,
		"potion of polymorph": true,
		"volcanic potion": true,
		"backroom bouncer": true,
		"dispatch kodo": true,
		"greater healing potion": true,
		"jinyu waterspeaker": true,
		"seadevil stinger": true,
		"shadow sensei": true,
		"alley armorsmith": true,
		"bomb squad": true,
		"doppelgangster": true,
		"drakonid operative": true,
		"grimestreet enforcer": true,
		"lotus agents": true,
		"second-rate bruiser": true,
		"spiked hogrider": true,
		"virmen sensei": true,
		"felfire potion": true,
		"kabal crystal runner": true,
		"grimestreet protector": true,
		"finders keepers": true,
		"meanstreet marshal": true,
		"weasel tunneler": true,
		"dirty rat": true,
		"mana geode": true,
		"sleep with the fishes": true,
		"blubber baron": true,
		"fel orc soulfiend": true,
		"manic soulcaster": true,
		"pilfered power": true,
		"rat pack": true,
		"small-time recruits": true,
		"unlicensed apothecary": true,
		"brass knuckles": true,
		"lotus illusionist": true,
		"burgly bully": true,
		"lotus assassin": true,
		"lunar visions": true,
		"piranha launcher": true,
		"defias cleaner": true,
		"dragonfire potion": true,
		"fight promoter": true,
		"kabal trafficker": true,
		"leatherclad hogleader": true,
		"luckydo buccaneer": true,
		"wind-up burglebot": true,
		"greater arcane missiles": true,
		"patches the pirate": true,
		"hobart grapplehammer": true,
		"auctionmaster beardo": true,
		"sergeant sally": true,
		"shaku, the collector": true,
		"wickerflame burnbristle": true,
		"genzo, the shark": true,
		"kazakus": true,
		"finja, the flying star": true,
		"knuckles": true,
		"raza the chained": true,
		"white eyes": true,
		"aya blackpaw": true,
		"madam goya": true,
		"wrathion": true,
		"don han'cho": true,
		"inkmaster solia": true,
		"krul the unshackled": true,
		"mayor noggenfogger": true,
		"kun the forgotten king": true,
		"arcane anomaly": true,
		"enchanted raven": true,
		"malchezaar's imp": true,
		"runic egg": true,
		"swashburglar": true,
		"kindly grandmother": true,
		"medivh's valet": true,
		"netherspite historian": true,
		"pompous thespian": true,
		"purify": true,
		"spirit claws": true,
		"cloaked huntress": true,
		"deadly fork": true,
		"nightbane templar": true,
		"pantry spider": true,
		"violet illusionist": true,
		"zoobot": true,
		"arcanosmith": true,
		"priest of the feast": true,
		"silvermoon portal": true,
		"wicked witchdoctor": true,
		"fool's bane": true,
		"ironforge portal": true,
		"kara kazham!": true,
		"menagerie magician": true,
		"menagerie warden": true,
		"firelands portal": true,
		"babbling book": true,
		"cat trick": true,
		"maelstrom portal": true,
		"protect the king!": true,
		"silverware golem": true,
		"avian watcher": true,
		"ethereal peddler": true,
		"onyx bishop": true,
		"book wyrm": true,
		"ivory knight": true,
		"moat lurker": true,
		"moonglade portal": true,
		"arcane giant": true,
		"moroes": true,
		"barnes": true,
		"prince malchezaar": true,
		"the curator": true,
		"medivh, the guardian": true,
		"bladed cultist": true,
		"divine strength": true,
		"fiery bat": true,
		"n'zoth's first mate": true,
		"on the hunt": true,
		"possessed villager": true,
		"primal fusion": true,
		"tentacle of n'zoth": true,
		"zealous initiate": true,
		"a light in the darkness": true,
		"beckoner of evil": true,
		"bilefin tidehunter": true,
		"duskboar": true,
		"mark of y'shaarj": true,
		"shatter": true,
		"stormcrack": true,
		"twilight geomancer": true,
		"twisted worgen": true,
		"am'gam rager": true,
		"carrion grub": true,
		"darkshire councilman": true,
		"feral rage": true,
		"ravaging ghoul": true,
		"shadow strike": true,
		"spawn of n'zoth": true,
		"squirming tentacle": true,
		"twilight elder": true,
		"twilight flamecaller": true,
		"aberrant berserker": true,
		"bloodhoof brave": true,
		"c'thun's chosen": true,
		"evolved kobold": true,
		"flamewreathed faceless": true,
		"hooded acolyte": true,
		"infested tauren": true,
		"polluted hoarder": true,
		"southsea squidface": true,
		"cult apothecary": true,
		"darkshire alchemist": true,
		"power word: tentacles": true,
		"psych-o-tron": true,
		"stand against darkness": true,
		"usher of souls": true,
		"dark arakkoa": true,
		"faceless summoner": true,
		"nerubian prophet": true,
		"bog creeper": true,
		"grotesque dragonhawk": true,
		"eldritch horror": true,
		"faceless behemoth": true,
		"forbidden ritual": true,
		"blood to ichor": true,
		"evolve": true,
		"journey below": true,
		"selfless hero": true,
		"cult sorcerer": true,
		"darkshire librarian": true,
		"undercity huckster": true,
		"addled grizzly": true,
		"bloodsail cultist": true,
		"disciple of c'thun": true,
		"forlorn stalker": true,
		"infest": true,
		"rallying blade": true,
		"silithid swarmer": true,
		"spreading madness": true,
		"steward of darkshire": true,
		"blackwater pirate": true,
		"demented frostcaller": true,
		"eater of secrets": true,
		"infested wolf": true,
		"klaxxi amber-weaver": true,
		"master of evolution": true,
		"midnight drake": true,
		"mire keeper": true,
		"shadow word: horror": true,
		"shifting shade": true,
		"corrupted healbot": true,
		"servant of yogg-saron": true,
		"twilight darkmender": true,
		"corrupted seer": true,
		"skeram cultist": true,
		"thing from below": true,
		"thistle tea": true,
		"ancient shieldbearer": true,
		"doomcaller": true,
		"forbidden flame": true,
		"forbidden healing": true,
		"forbidden shaping": true,
		"forbidden ancient": true,
		"vilefin inquisitor": true,
		"embrace the shadow": true,
		"eternal sentinel": true,
		"renounce darkness": true,
		"blood warriors": true,
		"cyclopian horror": true,
		"faceless shambler": true,
		"twilight summoner": true,
		"cabalist's tome": true,
		"crazed worshipper": true,
		"darkspeaker": true,
		"hammer of twilight": true,
		"shadowcaster": true,
		"tentacles for arms": true,
		"validated doomsayer": true,
		"ancient harbinger": true,
		"scaled nightmare": true,
		"wisps of the old gods": true,
		"giant sand worm": true,
		"blade of c'thun": true,
		"blood of the ancient one": true,
		"call of the wild": true,
		"doom!": true,
		"shifter zerus": true,
		"nat, the darkfisher": true,
		"fandral staghelm": true,
		"xaril, poisoned mind": true,
		"hallazeal the ascended": true,
		"princess huhuran": true,
		"herald volazj": true,
		"mukla, tyrant of the vale": true,
		"cho'gall": true,
		"hogger, doom of elwynn": true,
		"malkorok": true,
		"twin emperor vek'lor": true,
		"anomalus": true,
		"ragnaros, lightlord": true,
		"the boogeymonster": true,
		"soggoth the slitherer": true,
		"c'thun": true,
		"deathwing, dragonlord": true,
		"n'zoth, the corruptor": true,
		"y'shaarj, rage unbound": true,
		"yogg-saron, hope's end": true,
		"murloc tinyfin": true,
		"pit snake": true,
		"raven idol": true,
		"sacred trial": true,
		"tunnel trogg": true,
		"curse of rafaam": true,
		"dark peddler": true,
		"dart trap": true,
		"huge toad": true,
		"jeweled scarab": true,
		"museum curator": true,
		"desert camel": true,
		"fierce monkey": true,
		"forgotten torch": true,
		"mounted raptor": true,
		"gorillabot a-3": true,
		"keeper of uldaman": true,
		"rumbling elemental": true,
		"tomb pillager": true,
		"tomb spider": true,
		"anubisath sentinel": true,
		"ethereal conjurer": true,
		"entomb": true,
		"obsidian destroyer": true,
		"fossilized devilsaur": true,
		"cursed blade": true,
		"reliquary seeker": true,
		"explorer's hat": true,
		"unearthed raptor": true,
		"ancient shade": true,
		"animated armor": true,
		"eerie statue": true,
		"jungle moonkin": true,
		"excavated evil": true,
		"summoning stone": true,
		"wobbling runts": true,
		"everyfin is awesome": true,
		"anyfin can happen": true,
		"djinni of zephyrs": true,
		"naga sea witch": true,
		"sir finley mrrgglton": true,
		"brann bronzebeard": true,
		"elise starseeker": true,
		"reno jackson": true,
		"arch-thief rafaam": true,
		"brave archer": true,
		"buccaneer": true,
		"flash heal": true,
		"gadgetzan jouster": true,
		"living roots": true,
		"lowly squire": true,
		"power word: glory": true,
		"tournament attendee": true,
		"ancestral knowledge": true,
		"bear trap": true,
		"bolster": true,
		"boneguard lieutenant": true,
		"demonfuse": true,
		"druid of the saber": true,
		"flame juggler": true,
		"king's elekk": true,
		"lance carrier": true,
		"totem golem": true,
		"undercity valiant": true,
		"wrathguard": true,
		"argent horserider": true,
		"bash": true,
		"dragonhawk rider": true,
		"ice rager": true,
		"orgrimmar aspirant": true,
		"seal of champions": true,
		"silent knight": true,
		"silver hand regent": true,
		"spellslinger": true,
		"tuskarr totemic": true,
		"warhorse trainer": true,
		"dalaran aspirant": true,
		"evil heckler": true,
		"frigid snobold": true,
		"holy champion": true,
		"maiden of the lake": true,
		"murloc knight": true,
		"refreshment vendor": true,
		"tournament medic": true,
		"wildwalker": true,
		"clockwork knight": true,
		"flame lance": true,
		"kvaldir raider": true,
		"mukla's champion": true,
		"pit fighter": true,
		"shado-pan rider": true,
		"captured jormungar": true,
		"fearsome doomguard": true,
		"north sea kraken": true,
		"competitive spirit": true,
		"injured kvaldir": true,
		"alexstrasza's champion": true,
		"argent lance": true,
		"argent watchman": true,
		"convert": true,
		"cutpurse": true,
		"darnassus aspirant": true,
		"fallen hero": true,
		"sparring partner": true,
		"tiny knight of evil": true,
		"wyrmrest agent": true,
		"burgle": true,
		"coliseum manager": true,
		"effigy": true,
		"fencing coach": true,
		"healing wave": true,
		"king's defender": true,
		"light's champion": true,
		"polymorph: boar": true,
		"powershot": true,
		"saboteur": true,
		"shady dealer": true,
		"armored warhorse": true,
		"draenei totemcarver": true,
		"fist of jaraxxus": true,
		"savage combatant": true,
		"spawn of shadows": true,
		"ram wrangler": true,
		"thunder bluff valiant": true,
		"tuskarr jouster": true,
		"ball of spiders": true,
		"master jouster": true,
		"mogor's champion": true,
		"void crusher": true,
		"knight of the wild": true,
		"arcane blast": true,
		"confuse": true,
		"garrison commander": true,
		"lock and load": true,
		"beneath the grounds": true,
		"elemental destruction": true,
		"master of ceremonies": true,
		"mulch": true,
		"shadowfiend": true,
		"stablemaster": true,
		"astral communion": true,
		"charged hammer": true,
		"crowd favorite": true,
		"dreadsteed": true,
		"magnataur alpha": true,
		"poisoned blade": true,
		"twilight guardian": true,
		"recruiter": true,
		"coldarra drake": true,
		"dark bargain": true,
		"enter the coliseum": true,
		"grand crusader": true,
		"kodorider": true,
		"mysterious challenger": true,
		"sea reaver": true,
		"sideshow spelleater": true,
		"frost giant": true,
		"dreadscale": true,
		"eydis darkbane": true,
		"fjola lightbane": true,
		"gormok the impaler": true,
		"nexus-champion saraad": true,
		"bolf ramshield": true,
		"justicar trueheart": true,
		"the mistcaller": true,
		"the skeleton knight": true,
		"wilfred fizzlebang": true,
		"acidmaw": true,
		"chillmaw": true,
		"confessor paletress": true,
		"eadric the pure": true,
		"skycap'n kragg": true,
		"rhonin": true,
		"anub'arak": true,
		"aviana": true,
		"icehowl": true,
		"varian wrynn": true,
		"twilight whelp": true,
		"gang up": true,
		"quick shot": true,
		"blackwing technician": true,
		"druid of the flame": true,
		"imp gang boss": true,
		"axe flinger": true,
		"dragonkin sorcerer": true,
		"fireguard destroyer": true,
		"hungry dragon": true,
		"blackwing corruptor": true,
		"dragon's breath": true,
		"solemn vigil": true,
		"drakonid crusher": true,
		"volcanic drake": true,
		"dragon egg": true,
		"lava shock": true,
		"resurrect": true,
		"revenge": true,
		"demonwrath": true,
		"flamewaker": true,
		"core rager": true,
		"dark iron skulker": true,
		"dragon consort": true,
		"grim patron": true,
		"volcanic lumberer": true,
		"emperor thaurissan": true,
		"rend blackhand": true,
		"chromaggus": true,
		"majordomo executus": true,
		"nefarian": true,
		"clockwork gnome": true,
		"cogmaster": true,
		"warbot": true,
		"annoy-o-tron": true,
		"anodized robo cub": true,
		"crackle": true,
		"darkbomb": true,
		"explosive sheep": true,
		"flamecannon": true,
		"gilblin stalker": true,
		"glaivezooka": true,
		"goblin auto-barber": true,
		"mechwarper": true,
		"micro machine": true,
		"puddlestomper": true,
		"seal of light": true,
		"shielded minibot": true,
		"ship's cannon": true,
		"shrinkmeister": true,
		"snowchugger": true,
		"stonesplinter trogg": true,
		"whirling zap-o-matic": true,
		"flying machine": true,
		"gnomeregan infantry": true,
		"ogre brute": true,
		"ogre warmaul": true,
		"spider tank": true,
		"tinkertown technician": true,
		"velen's chosen": true,
		"burly rockjaw trogg": true,
		"lost tallstrider": true,
		"mechanical yeti": true,
		"piloted shredder": true,
		"tinker's sharpsword oil": true,
		"antique healbot": true,
		"cobra shot": true,
		"druid of the fang": true,
		"floating watcher": true,
		"salty dog": true,
		"force-tank max": true,
		"target dummy": true,
		"light of the naaru": true,
		"call pet": true,
		"mistress of pain": true,
		"one-eyed cheat": true,
		"shadowboxer": true,
		"unstable portal": true,
		"vitality totem": true,
		"gnomish experimenter": true,
		"goblin sapper": true,
		"grove tender": true,
		"illuminator": true,
		"iron sensei": true,
		"lil' exorcist": true,
		"metaltooth leaper": true,
		"muster for battle": true,
		"powermace": true,
		"scarlet purifier": true,
		"soot spewer": true,
		"arcane nullifier x-21": true,
		"dunemaul shaman": true,
		"fel cannon": true,
		"goblin blastmage": true,
		"imp-losion": true,
		"jeeves": true,
		"kezan mystic": true,
		"screwjank clunker": true,
		"bomb lobber": true,
		"cobalt guardian": true,
		"king of beasts": true,
		"madder bomber": true,
		"ogre ninja": true,
		"siege engine": true,
		"upgraded repair bot": true,
		"mech-bear-cat": true,
		"recycle": true,
		"shieldmaiden": true,
		"shadowbomber": true,
		"feign death": true,
		"recombobulator": true,
		"steamwheedle sniper": true,
		"bouncing blade": true,
		"coghammer": true,
		"cogmaster's wrench": true,
		"hobgoblin": true,
		"ancestor's call": true,
		"echo of medivh": true,
		"enhance-o mechano": true,
		"mini-mage": true,
		"sabotage": true,
		"siltfin spiritwalker": true,
		"wee spellstopper": true,
		"demonheart": true,
		"fel reaver": true,
		"junkbot": true,
		"quartermaster": true,
		"anima golem": true,
		"dark wispers": true,
		"lightbomb": true,
		"piloted sky golem": true,
		"crush": true,
		"tree of life": true,
		"clockwork giant": true,
		"blingtron 3000": true,
		"bolvar fordragon": true,
		"hemet nesingwary": true,
		"mimiron's head": true,
		"vol'jin": true,
		"gazlowe": true,
		"iron juggernaut": true,
		"mogor the ogre": true,
		"toshley": true,
		"trade prince gallywix": true,
		"dr. boom": true,
		"flame leviathan": true,
		"gahz'rilla": true,
		"malorne": true,
		"neptulon": true,
		"troggzor the earthinator": true,
		"foe reaper 4000": true,
		"sneed's old shredder": true,
		"mal'ganis": true,
		"mekgineer thermaplugg": true,
		"avenge": true,
		"undertaker": true,
		"webspinner": true,
		"zombie chow": true,
		"haunted creeper": true,
		"mad scientist": true,
		"nerub'ar weblord": true,
		"reincarnate": true,
		"unstable ghoul": true,
		"dancing swords": true,
		"dark cultist": true,
		"duplicate": true,
		"stoneskin gargoyle": true,
		"anub'ar ambusher": true,
		"death's bite": true,
		"poison seeds": true,
		"voidcaller": true,
		"spectral knight": true,
		"nerubian egg": true,
		"deathlord": true,
		"wailing soul": true,
		"sludge belcher": true,
		"echoing ooze": true,
		"shade of naxxramas": true,
		"baron rivendare": true,
		"feugen": true,
		"loatheb": true,
		"stalagg": true,
		"maexxna": true,
		"kel'thuzad": true,
		"circle of healing": true,
		"inner rage": true,
		"shadowstep": true,
		"silence": true,
		"wisp": true,
		"abusive sergeant": true,
		"argent squire": true,
		"blessing of wisdom": true,
		"blood imp": true,
		"cold blood": true,
		"dust devil": true,
		"earth shock": true,
		"eye for an eye": true,
		"flame imp": true,
		"forked lightning": true,
		"inner fire": true,
		"leper gnome": true,
		"lightning bolt": true,
		"mana wyrm": true,
		"naturalize": true,
		"noble sacrifice": true,
		"redemption": true,
		"repentance": true,
		"shieldbearer": true,
		"southsea deckhand": true,
		"worgen infiltrator": true,
		"young dragonhawk": true,
		"amani berserker": true,
		"argent protector": true,
		"battle rage": true,
		"betrayal": true,
		"bloodsail raider": true,
		"cruel taskmaster": true,
		"defias ringleader": true,
		"demonfire": true,
		"dire wolf alpha": true,
		"eviscerate": true,
		"explosive trap": true,
		"faerie dragon": true,
		"freezing trap": true,
		"loot hoarder": true,
		"mad bomber": true,
		"power of the wild": true,
		"rampage": true,
		"scavenging hyena": true,
		"slam": true,
		"snipe": true,
		"sorcerer's apprentice": true,
		"stormforged axe": true,
		"wrath": true,
		"youthful brewmaster": true,
		"acolyte of pain": true,
		"deadly shot": true,
		"earthen ring farseer": true,
		"flesheating ghoul": true,
		"harvest golem": true,
		"ice barrier": true,
		"ironbeak owl": true,
		"jungle panther": true,
		"mark of nature": true,
		"mirror entity": true,
		"raging worgen": true,
		"scarlet crusader": true,
		"sense demons": true,
		"tauren warrior": true,
		"thoughtsteal": true,
		"thrallmar farseer": true,
		"unbound elemental": true,
		"unleash the hounds": true,
		"ancient brewmaster": true,
		"arathi weaponsmith": true,
		"cone of cold": true,
		"cult master": true,
		"dark iron dwarf": true,
		"dread corsair": true,
		"lightspawn": true,
		"mogu'shan warden": true,
		"silvermoon guardian": true,
		"soul of the forest": true,
		"spellbreaker": true,
		"summoning portal": true,
		"druid of the claw": true,
		"fen creeper": true,
		"silver hand knight": true,
		"spiteful smith": true,
		"stranglethorn tiger": true,
		"venture co. mercenary": true,
		"frost elemental": true,
		"priestess of elune": true,
		"temple enforcer": true,
		"windfury harpy": true,
		"angry chicken": true,
		"bloodsail corsair": true,
		"lightwarden": true,
		"murloc tidecaller": true,
		"savagery": true,
		"secretkeeper": true,
		"upgrade!": true,
		"young priestess": true,
		"ancestral spirit": true,
		"ancient watcher": true,
		"armorsmith": true,
		"commanding shout": true,
		"crazed alchemist": true,
		"equality": true,
		"flare": true,
		"knife juggler": true,
		"lightwell": true,
		"mana addict": true,
		"mana wraith": true,
		"master swordsmith": true,
		"misdirection": true,
		"pint-sized summoner": true,
		"sunfury protector": true,
		"wild pyromancer": true,
		"alarm-o-bot": true,
		"aldor peacekeeper": true,
		"arcane golem": true,
		"coldlight oracle": true,
		"coldlight seer": true,
		"counterspell": true,
		"demolisher": true,
		"divine favor": true,
		"eaglehorn bow": true,
		"emperor cobra": true,
		"felguard": true,
		"feral spirit": true,
		"frothing berserker": true,
		"headcrack": true,
		"imp master": true,
		"injured blademaster": true,
		"kirin tor mage": true,
		"lava burst": true,
		"lightning storm": true,
		"mana tide totem": true,
		"mind control tech": true,
		"perdition's blade": true,
		"questing adventurer": true,
		"si:7 agent": true,
		"vaporize": true,
		"void terror": true,
		"ancient mage": true,
		"auchenai soulpriest": true,
		"bite": true,
		"blade flurry": true,
		"defender of argus": true,
		"ethereal arcanist": true,
		"keeper of the grove": true,
		"mass dispel": true,
		"master of disguise": true,
		"mortal strike": true,
		"shadow madness": true,
		"shadowflame": true,
		"twilight drake": true,
		"violet teacher": true,
		"abomination": true,
		"blessed champion": true,
		"doomguard": true,
		"explosive shot": true,
		"holy wrath": true,
		"nourish": true,
		"stampeding kodo": true,
		"starfall": true,
		"argent commander": true,
		"blizzard": true,
		"gadgetzan auctioneer": true,
		"holy fire": true,
		"savannah highmane": true,
		"siphon soul": true,
		"sunwalker": true,
		"ravenholdt assassin": true,
		"preparation": true,
		"bestial wrath": true,
		"hungry crab": true,
		"shield slam": true,
		"doomsayer": true,
		"patient assassin": true,
		"snake trap": true,
		"blood knight": true,
		"far sight": true,
		"ice block": true,
		"murloc warleader": true,
		"shadowform": true,
		"southsea captain": true,
		"spellbender": true,
		"sword of justice": true,
		"mindgames": true,
		"pit lord": true,
		"bane of doom": true,
		"big game hunter": true,
		"brawl": true,
		"doomhammer": true,
		"earth elemental": true,
		"faceless manipulator": true,
		"force of nature": true,
		"avenging wrath": true,
		"cabal shadow priest": true,
		"kidnapper": true,
		"ancient of lore": true,
		"ancient of war": true,
		"gladiator's longbow": true,
		"gorehowl": true,
		"lay on hands": true,
		"twisting nether": true,
		"pyroblast": true,
		"sea giant": true,
		"mountain giant": true,
		"molten giant": true,
		"bloodmage thalnos": true,
		"lorewalker cho": true,
		"millhouse manastorm": true,
		"nat pagle": true,
		"edwin vancleef": true,
		"king mukla": true,
		"tinkmaster overspark": true,
		"captain greenskin": true,
		"harrison jones": true,
		"leeroy jenkins": true,
		"cairne bloodhoof": true,
		"hogger": true,
		"illidan stormrage": true,
		"the beast": true,
		"the black knight": true,
		"archmage antonidas": true,
		"baron geddon": true,
		"prophet velen": true,
		"al'akir the windlord": true,
		"grommash hellscream": true,
		"gruul": true,
		"tirion fordring": true,
		"alexstrasza": true,
		"cenarius": true,
		"king krush": true,
		"lord jaraxxus": true,
		"malygos": true,
		"nozdormu": true,
		"onyxia": true,
		"ysera": true,
		"deathwing": true,
		"ancestral healing": true,
		"backstab": true,
		"innervate": true,
		"moonfire": true,
		"sacrificial pact": true,
		"totemic might": true,
		"arcane missiles": true,
		"arcane shot": true,
		"blessing of might": true,
		"charge": true,
		"claw": true,
		"corruption": true,
		"deadly poison": true,
		"elven archer": true,
		"frost shock": true,
		"goldshire footman": true,
		"grimscale oracle": true,
		"hand of protection": true,
		"holy smite": true,
		"humility": true,
		"hunter's mark": true,
		"light's justice": true,
		"mind vision": true,
		"mirror image": true,
		"mortal coil": true,
		"murloc raider": true,
		"northshire cleric": true,
		"power word: shield": true,
		"sinister strike": true,
		"soulfire": true,
		"stonetusk boar": true,
		"timber wolf": true,
		"tracking": true,
		"voidwalker": true,
		"voodoo doctor": true,
		"whirlwind": true,
		"acidic swamp ooze": true,
		"arcane explosion": true,
		"bloodfen raptor": true,
		"bluegill warrior": true,
		"cleave": true,
		"divine spirit": true,
		"execute": true,
		"fiery war axe": true,
		"flametongue totem": true,
		"frostbolt": true,
		"frostwolf grunt": true,
		"heroic strike": true,
		"holy light": true,
		"kobold geomancer": true,
		"mark of the wild": true,
		"mind blast": true,
		"murloc tidehunter": true,
		"novice engineer": true,
		"river crocolisk": true,
		"rockbiter weapon": true,
		"sap": true,
		"shadow word: pain": true,
		"shiv": true,
		"succubus": true,
		"wild growth": true,
		"windfury": true,
		"animal companion": true,
		"arcane intellect": true,
		"dalaran mage": true,
		"drain life": true,
		"fan of knives": true,
		"frost nova": true,
		"healing touch": true,
		"hex": true,
		"ironforge rifleman": true,
		"ironfur grizzly": true,
		"kill command": true,
		"magma rager": true,
		"raid leader": true,
		"razorfen hunter": true,
		"savage roar": true,
		"shadow bolt": true,
		"shadow word: death": true,
		"shattered sun cleric": true,
		"shield block": true,
		"silverback patriarch": true,
		"warsong commander": true,
		"wolfrider": true,
		"blessing of kings": true,
		"chillwind yeti": true,
		"consecration": true,
		"dragonling mechanic": true,
		"fireball": true,
		"gnomish inventor": true,
		"hammer of wrath": true,
		"hellfire": true,
		"houndmaster": true,
		"kor'kron elite": true,
		"multi-shot": true,
		"oasis snapjaw": true,
		"ogre magi": true,
		"polymorph": true,
		"sen'jin shieldmasta": true,
		"stormwind knight": true,
		"swipe": true,
		"truesilver champion": true,
		"water elemental": true,
		"windspeaker": true,
		"arcanite reaper": true,
		"assassin's blade": true,
		"assassinate": true,
		"bloodlust": true,
		"booty bay bodyguard": true,
		"darkscale healer": true,
		"frostwolf warlord": true,
		"gurubashi berserker": true,
		"holy nova": true,
		"nightblade": true,
		"starving buzzard": true,
		"stormpike commando": true,
		"tundra rhino": true,
		"archmage": true,
		"boulderfist ogre": true,
		"dread infernal": true,
		"fire elemental": true,
		"lord of the arena": true,
		"reckless rocketeer": true,
		"starfire": true,
		"vanish": true,
		"core hound": true,
		"flamestrike": true,
		"guardian of kings": true,
		"sprint": true,
		"stormwind champion": true,
		"war golem": true,
		"ironbark protector": true,
		"mind control": true,
		"conceal": true,
		"ice lance": true,
		"power overwhelming": true,
		"azure drake": true,
		"captain's parrot": true,
		"old murk-eye": true,
		"elite tauren chieftain": true,
		"gelbin mekkatorque": true,
		"sylvanas windrunner": true,
		"ragnaros the firelord": true,
	}
}
